# Generated by Django 3.1.6 on 2021-05-17 17:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='uploaded_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReviewAiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='review title', max_length=225)),
                ('detail', models.TextField()),
                ('rating', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('uploaded_on', models.DateTimeField(auto_now=True)),
                ('aimodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.aimodel')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
