# Generated by Django 3.1.6 on 2021-05-18 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0002_auto_20210517_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='uploader',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
